name: Laravel Deployment
concurrency: production_environment

on:
  workflow_call:
    inputs:
      php-version:
        description: "PHP version"
        required: false
        default: "8.3"
        type: string
      deploy-namespace:
        description: "Deploy Namespace"
        required: false
        default: ${{ github.ref_name }}
        type: string
    # Read here why secrets should be passed by caller workflow. Resuable workflow don't have direct access to secrets.
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    # > Workflows that call reusable workflows in the same organization or enterprise can use the inherit keyword to implicitly pass the secrets.
    secrets:
      PRIVATE_KEY:
        description: "Private key for deployment"
        required: true
      VAULT_ADDR:
        description: "Vault address"
        required: true
      VAULT_TOKEN:
        description: "Vault token"
        required: true
      VAULT_PATH:
        description: "Vault path"
        required: true

jobs:
  deploy-laravel-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ inputs.php-version }}

      - name: Fetch Vault Path and Pass it to env variable
        env:
          VAULT_PATH: ${{ secrets.VAULT_PATH }}
        run: |
          # Fetch the JSON data from the Vault path
          vault_data=${{ env.VAULT_PATH }}

          # echo $vault_data > vault_data.json

          # vault_data=$(jq -c '.' './vault_data.json')

          # Extract the value using jq
          secret_value=$(echo "$vault_data" | jq -r '.["${{ inputs.deploy-namespace }}"]')

          echo "SECRET_PATH=${secret_value}" >> "$GITHUB_ENV"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Deploy
        uses: deployphp/action@master
        env:
          SECRET_PATH: ${{ env.SECRET_PATH }}
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy ${{ inputs.deploy-namespace }} -o vault_addr=${{ secrets.VAULT_ADDR }} -o secret_path=${{ env.SECRET_PATH }} -o vault_token=${{ secrets.VAULT_TOKEN }}
          verbosity: -vvv
